server:
  port: 30308
spring:
  application:
    name: bread
  datasource:
    username: feed
    password: feed
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/feeding
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
starter:
  cors:
    allowedOrigins:
      - "*"
    allowedMethods:
      - "*"
    allowedHeaders:
      - "*"
  life:
    updater:
      cron: "0 56 22 * * *"